[package]
name = "ilias-extract"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
zip = "6.0.0"
regex = "1.12.2"
calamine = "0.32.0"
tempfile = "3.23.0"
chrono = "0.4.42"
colored = "3.0.0"
